<?php

namespace AppBundle\Repository;

/**
 * WeekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeekRepository extends \Doctrine\ORM\EntityRepository
{
}
